In [1]:
%matplotlib inline
%matplotlib notebook

In [2]:
#import warnings
#warnings.filterwarnings('ignore')

from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt

from sklearn import datasets
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn import metrics

### Loading the HD_labelled_50 dataset

In [3]:
dataset = pd.read_csv('HD_labelled_50.csv')

Head function returns the first n rows for the object based on position, here n = 5.

In [4]:
dataset.head()

Age     Sex   CP   TRestBPS   Chol   FBS   RestECG   ThalAch   ExAng   \
0      63     1    1        145    233     1         2       150       0   
1      67     1    4        160    286     0         2       108       1   
2      67     1    4        120    229     0         2       129       1   
3      37     1    3        130    250     0         0       187       0   
4      41     0    2        130    204     0         2       172       0   

   OldPeak  Slope  CA  Thal   Label  
0      2.3      3   0      6      0  
1      1.5      2   3      3      1  
2      2.6      2   2      7      1  
3      3.5      3   0      3      0  
4      1.4      1   0      3      0

### Renaming the attribute names

In [5]:
dataset.columns = ['A','B','C','D','E','F','G','H','I','J','K','L','M','Label']

Drop function is used to elimate the values from the table, here we are dropping the column 'A' and 'B'.

In [6]:
z = dataset.drop(['A','B'], axis =  1)

Displaying the values after dropping the columns 'A' and 'B'.

In [7]:
z

C    D    E  F  G    H  I    J  K  L  M  Label
0   1  145  233  1  2  150  0  2.3  3  0  6      0
1   4  160  286  0  2  108  1  1.5  2  3  3      1
2   4  120  229  0  2  129  1  2.6  2  2  7      1
3   3  130  250  0  0  187  0  3.5  3  0  3      0
4   2  130  204  0  2  172  0  1.4  1  0  3      0
5   2  120  236  0  0  178  0  0.8  1  0  3      0
6   4  140  268  0  2  160  0  3.6  3  2  3      1
7   4  120  354  0  0  163  1  0.6  1  0  3      0
8   4  130  254  0  2  147  0  1.4  2  1  7      1
9   4  140  203  1  2  155  1  3.1  3  0  7      1
10  4  140  192  0  0  148  0  0.4  2  0  6      0
11  2  140  294  0  2  153  0  1.3  2  0  3      0
12  3  130  256  1  2  142  1  0.6  2  1  6      1
13  2  120  263  0  0  173  0  0.0  1  0  7      0
14  3  172  199  1  0  162  0  0.5  1  0  7      0
15  3  150  168  0  0  174  0  1.6  1  0  3      0
16  2  110  229  0  0  168  0  1.0  3  0  7      1
17  4  140  239  0  0  160  0  1.2  1  0  3      0
18  3  130  275  0  0  139  0  0.2  1  0  3      0
19  2  130  266  0  0  171  0  0.6  1  0  3      0
20  1  110  211  0  2  144  1  1.8  2  0  3      0
21  1  150  283  1  2  162  0  1.0  1  0  3      0
22  2  120  284  0  2  160  0  1.8  2  0  3      1
23  3  132  224  0  2  173  0  3.2  1  2  7      1
24  4  130  206  0  2  132  1  2.4  2  2  7      1
25  3  120  219  0  0  158  0  1.6  2  0  3      0
26  3  120  340  0  0  172  0  0.0  1  0  3      0
27  1  150  226  0  0  114  0  2.6  3  0  3      0
28  4  150  247  0  0  171  0  1.5  1  0  3      0
29  4  110  167  0  2  114  1  2.0  2  0  7      1
30  1  140  239  0  0  151  0  1.8  1  2  3      0
31  4  117  230  1  0  160  1  1.4  1  2  7      1
32  3  140  335  0  0  158  0  0.0  1  0  3      1
33  4  135  234  0  0  161  0  0.5  2  0  7      0
34  3  130  233  0  0  179  1  0.4  1  0  3      0
35  4  140  226  0  0  178  0  0.0  1  0  3      0
36  4  120  177  0  2  120  1  2.5  2  0  7      1
37  4  150  276  0  2  112  1  0.6  2  1  6      1
38  4  132  353  0  0  132  1  1.2  2  1  7      1
39  3  150  243  1  0  137  1  1.0  2  0  3      0
40  4  150  225  0  2  114  0  1.0  2  3  7      1
41  1  140  199  0  0  178  1  1.4  1  0  7      0
42  2  160  302  0  0  162  0  0.4  1  2  3      0
43  3  150  212  1  0  157  0  1.6  1  0  3      0
44  4  130  330  0  2  169  0  0.0  1  0  3      1
45  3  112  230  0  2  165  0  2.5  2  1  7      1
46  3  110  175  0  0  123  0  0.6  1  0  3      0
47  4  150  243  0  2  128  0  2.6  2  0  7      1
48  3  140  417  1  2  157  0  0.8  1  1  3      0
49  3  130  197  1  2  152  0  1.2  3  0  3      0

In [8]:
dataset['Label'].unique()

array([0, 1], dtype=int64)

In [9]:
x = dataset.iloc[:,[2,3,4,6,7,9,10,11,12]].values
y = dataset.iloc[:,[1,5,8,3]].values

In [10]:
y_train =  dataset['Label']

In [11]:
x_train =  dataset.drop('Label', axis = 1)

In [12]:
x_train

A  B  C    D    E  F  G    H  I    J  K  L  M
0   63  1  1  145  233  1  2  150  0  2.3  3  0  6
1   67  1  4  160  286  0  2  108  1  1.5  2  3  3
2   67  1  4  120  229  0  2  129  1  2.6  2  2  7
3   37  1  3  130  250  0  0  187  0  3.5  3  0  3
4   41  0  2  130  204  0  2  172  0  1.4  1  0  3
5   56  1  2  120  236  0  0  178  0  0.8  1  0  3
6   62  0  4  140  268  0  2  160  0  3.6  3  2  3
7   57  0  4  120  354  0  0  163  1  0.6  1  0  3
8   63  1  4  130  254  0  2  147  0  1.4  2  1  7
9   53  1  4  140  203  1  2  155  1  3.1  3  0  7
10  57  1  4  140  192  0  0  148  0  0.4  2  0  6
11  56  0  2  140  294  0  2  153  0  1.3  2  0  3
12  56  1  3  130  256  1  2  142  1  0.6  2  1  6
13  44  1  2  120  263  0  0  173  0  0.0  1  0  7
14  52  1  3  172  199  1  0  162  0  0.5  1  0  7
15  57  1  3  150  168  0  0  174  0  1.6  1  0  3
16  48  1  2  110  229  0  0  168  0  1.0  3  0  7
17  54  1  4  140  239  0  0  160  0  1.2  1  0  3
18  48  0  3  130  275  0  0  139  0  0.2  1  0  3
19  49  1  2  130  266  0  0  171  0  0.6  1  0  3
20  64  1  1  110  211  0  2  144  1  1.8  2  0  3
21  58  0  1  150  283  1  2  162  0  1.0  1  0  3
22  58  1  2  120  284  0  2  160  0  1.8  2  0  3
23  58  1  3  132  224  0  2  173  0  3.2  1  2  7
24  60  1  4  130  206  0  2  132  1  2.4  2  2  7
25  50  0  3  120  219  0  0  158  0  1.6  2  0  3
26  58  0  3  120  340  0  0  172  0  0.0  1  0  3
27  66  0  1  150  226  0  0  114  0  2.6  3  0  3
28  43  1  4  150  247  0  0  171  0  1.5  1  0  3
29  40  1  4  110  167  0  2  114  1  2.0  2  0  7
30  69  0  1  140  239  0  0  151  0  1.8  1  2  3
31  60  1  4  117  230  1  0  160  1  1.4  1  2  7
32  64  1  3  140  335  0  0  158  0  0.0  1  0  3
33  59  1  4  135  234  0  0  161  0  0.5  2  0  7
34  44  1  3  130  233  0  0  179  1  0.4  1  0  3
35  42  1  4  140  226  0  0  178  0  0.0  1  0  3
36  43  1  4  120  177  0  2  120  1  2.5  2  0  7
37  57  1  4  150  276  0  2  112  1  0.6  2  1  6
38  55  1  4  132  353  0  0  132  1  1.2  2  1  7
39  61  1  3  150  243  1  0  137  1  1.0  2  0  3
40  65  0  4  150  225  0  2  114  0  1.0  2  3  7
41  40  1  1  140  199  0  0  178  1  1.4  1  0  7
42  71  0  2  160  302  0  0  162  0  0.4  1  2  3
43  59  1  3  150  212  1  0  157  0  1.6  1  0  3
44  61  0  4  130  330  0  2  169  0  0.0  1  0  3
45  58  1  3  112  230  0  2  165  0  2.5  2  1  7
46  51  1  3  110  175  0  0  123  0  0.6  1  0  3
47  50  1  4  150  243  0  2  128  0  2.6  2  0  7
48  65  0  3  140  417  1  2  157  0  0.8  1  1  3
49  53  1  3  130  197  1  2  152  0  1.2  3  0  3

In [13]:
y_train

0     0
1     1
2     1
3     0
4     0
5     0
6     1
7     0
8     1
9     1
10    0
11    0
12    1
13    0
14    0
15    0
16    1
17    0
18    0
19    0
20    0
21    0
22    1
23    1
24    1
25    0
26    0
27    0
28    0
29    1
30    0
31    1
32    1
33    0
34    0
35    0
36    1
37    1
38    1
39    0
40    1
41    0
42    0
43    0
44    1
45    1
46    0
47    1
48    0
49    0
Name: Label, dtype: int64

Normalize data: the unit of measurement might differ so lets normalize the data before building the model

In [14]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)

Split data into train and test.  

In [15]:
# split data into train and test
# from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.3, random_state=0)

Generate the decision tree using the training data and the entropy-based informaion gain

In [16]:
clf = tree.DecisionTreeClassifier(criterion = 'entropy', random_state=0, min_samples_leaf = 3)
clf.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

Calculate the performance metrics = accuracy and confusion matrix for train and test data 

In [17]:
# generate evaluation metrics
print ("Train - Accuracy :", metrics.accuracy_score(y_train, clf.predict(x_train)))
print ("Train - Confusion matrix :\n", metrics.confusion_matrix(y_train, clf.predict(x_train)))
print ("Train - classification report :\n", metrics.classification_report(y_train, clf.predict(x_train)))

print ("Test - Accuracy :", metrics.accuracy_score(y_test, clf.predict(x_test)))
print ("Test - Confusion matrix :\n",metrics.confusion_matrix(y_test, clf.predict(x_test)))
print ("Test - classification report :\n", metrics.classification_report(y_test, clf.predict(x_test)))

Train - Accuracy : 0.9142857142857143
Train - Confusion matrix :
 [[18  1]
 [ 2 14]]
Train - classification report :
               precision    recall  f1-score   support

           0       0.90      0.95      0.92        19
           1       0.93      0.88      0.90        16

    accuracy                           0.91        35
   macro avg       0.92      0.91      0.91        35
weighted avg       0.92      0.91      0.91        35

Test - Accuracy : 0.8
Test - Confusion matrix :
 [[11  0]
 [ 3  1]]
Test - classification report :
               precision    recall  f1-score   support

           0       0.79      1.00      0.88        11
           1       1.00      0.25      0.40         4

    accuracy                           0.80        15
   macro avg       0.89      0.62      0.64        15
weighted avg       0.84      0.80      0.75        15



### Visualize Decision Tree 

In [18]:
tree.export_graphviz(clf, out_file='tree.dot')    

from sklearn.externals.six import StringIO  
import pydot 
out_data = StringIO() 
tree.export_graphviz(clf, out_file=out_data,
                    feature_names=dataset.columns[:13],
                    class_names=clf.classes_.astype(int).astype(str),
                   # class_names=dataset.columns[:10],
                    filled=True, rounded=True,
                    special_characters=True,
                    node_ids=1,) 
graph = pydot.graph_from_dot_data(out_data.getvalue()) 
graph[0].write_pdf("dataset_eval.pdf")  # save to pdf

from IPython.display import IFrame
IFrame("dataset_eval.pdf", width=600, height=600)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
